UPDATE Tracks SET layout_image = 'bahrain.png' WHERE country = 'Bahrain';
UPDATE Tracks SET layout_image = 'saudi_arabia.png' WHERE country = 'Saudi Arabia';
UPDATE Tracks SET layout_image = 'australia.png' WHERE country = 'Australia';
UPDATE Tracks SET layout_image = 'japan.png' WHERE country = 'Japan';
UPDATE Tracks SET layout_image = 'china.png' WHERE country = 'China';
UPDATE Tracks SET layout_image = 'miami.png' WHERE country = 'Miami';
UPDATE Tracks SET layout_image = 'emilia-romagna.png' WHERE country = 'Emilia-Romagna';
UPDATE Tracks SET layout_image = 'monaco.png' WHERE country = 'Monaco';
UPDATE Tracks SET layout_image = 'canada.png' WHERE country = 'Canada';
UPDATE Tracks SET layout_image = 'spain.png' WHERE country = 'Spain';
UPDATE Tracks SET layout_image = 'austria.png' WHERE country = 'Austria';
UPDATE Tracks SET layout_image = 'great_britain.png' WHERE country = 'Great Britain';
UPDATE Tracks SET layout_image = 'hungary.png' WHERE country = 'Hungary';
UPDATE Tracks SET layout_image = 'belgium.png' WHERE country = 'Belgium';
UPDATE Tracks SET layout_image = 'netherlands.png' WHERE country = 'Netherlands';
UPDATE Tracks SET layout_image = 'italy.png' WHERE country = 'Italy';
UPDATE Tracks SET layout_image = 'azerbaijan.png' WHERE country = 'Azerbaijan';
UPDATE Tracks SET layout_image = 'singapore.png' WHERE country = 'Singapore';
UPDATE Tracks SET layout_image = 'united_states.png' WHERE name = 'Circuit of the Americas';
UPDATE Tracks SET layout_image = 'mexico.png' WHERE country = 'Mexico';
UPDATE Tracks SET layout_image = 'brazil.png' WHERE country = 'Brazil';
UPDATE Tracks SET layout_image = 'las_vegas.png' WHERE name = 'Las Vegas Strip';
UPDATE Tracks SET layout_image = 'qatar.png' WHERE country = 'Qatar';
UPDATE Tracks SET layout_image = 'abu_dhabi.png' WHERE country = 'Abu Dhabi';